### ISSUE TITLE
Not able to start Chrome & Firefox containers with Zalenium

### ISSUE THREAD

**Issue by srinuuk** [elgalu/docker-selenium#176]
#### Operating System
- [x ] I provided my operating system name and version, e.g. output of `uname -a`
Darwin 24f094ea3286 16.7.0 Darwin Kernel Version 16.7.0
#### Image version
- [ x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [ x] I have latest version of docker and I will specify here the output of `docker --version`
Docker version 17.06.2-ce
- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_
- [x ] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`
docker-compose version 1.14.0
- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

When I start Zalenium with Saucelabs enabled I am getting below error. Selenium containers for firefox and chrome not getting started. When I run without saucelabs enabled Chrome and Firefox containers are up without any issues.  Any thoughts why we get 'Home name' may not be null error? I have also opened issue with Zalenium but pending. I though of posting the issues here also since error actually getting with Chrome and Firefox. Some conflict is there, not able to identify what the issue is. Please suggest.

15:39:41.162 [qtp2041605291-15] WARN  o.s.jetty9.server.HttpChannel - /grid/register
java.security.InvalidParameterException: Error: Host name may not be null
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:357)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:103)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:110)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.seleniumhq.jetty9.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:748)

**Comment by elgalu** [comment]
I see you also opened this issue https://github.com/zalando/zalenium/issues/253 so I will close here and let's keep it in one place (Zalenium) until there is something specific to be done docker-selenium side.
