### ISSUE TITLE
parallel tests get occasional "cannot forward the request" error

### ISSUE THREAD

**Issue by borisivan** [elgalu/docker-selenium#215]
#### Operating System
Both SLES 12 and Ubuntu 16.04

#### Image version
Every suite execution (multiple times per day) is preceded by a docker pull. Has been happening forever, but with greater frequency lately. In other words, I'm always running the latest, within 3-4 hours max of it being released

#### Docker version
ubuntu: 17.12.0-ce, build c97c6d6
SLES 12 GA: 17.04.0-ce, build 78d1802

Occasionally (used to be once every 4-5 suite runs of 120 tests -- is now 1-2 times per suite run of 120 tests), I get a cannot forward the request <ip>:<port> failed to respond message. This can be mid test. This is with zalenium.

It's occurring too frequently at this point. Can you help me understand what could possibly be occurring?

From my test's point of view -- mid test:

```
org.openqa.selenium.WebDriverException: cannot forward the request 172.17.0.7:40005 failed to respond
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:398)
```

From the master zalenium container:

```
org.apache.http.NoHttpResponseException: 172.17.0.7:40005 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:462)
        at org.openqa.grid.internal.TestSession.forward(TestSession.java:243)
        at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:98)
```

Does this imply that the problem must be a problem with selenium grid / Zalenium? Or is it possible that anything that I could be doing, could be influencing this? I am running 6 tests in parallel, and I do feel that I haven't constructed my suite properly re: thread safe re: a threadLocal implementation or some other solution. Every test class that I have has it's own webDriver, but that is also used when instantiating a class that is used as a processing library, that sets it's own local WebDriver to be what was passed when I instantiate it, from that class. This works, other than the once or twice out of 140 large tests running 6 in parallel.

Just trying to understand what the 'cannot forward' and 'failed to respond' could imply here. Thanks for any assistance.

**Comment by elgalu** [comment]
Hi, thanks for reporting.

Could you open Zalenium issues in the Zalenium project? that would be great.
