### ISSUE TITLE
FORWARDING_TO_NODE_FAILED

### ISSUE THREAD

**Issue by karl0ss** [elgalu/docker-selenium#316]
If I run my container locally on my mac, and execute my tests via Webdriver.io to the local docker container of elgalu/selenium, everything works, but when I am trying to execute in my jenkins pipeline, and connecting to the container via a jenkins slave, it fails and gives me the error FORWARDING_TO_NODE_FAILED...

Can't seem to find anything online to help me? hope someone can..

Thanks

```
[1;30m[10:34:40] [0m 	Failed to take screenshot on reject: 	 {"message":"Session [997b7217c7aded99c924d37b8f64c662] was terminated due to FORWARDING_TO_NODE_FAILED","type":"RuntimeError","seleniumStack":{"type":"UnknownError","message":"An unknown server-side error occurred while processing the command.","orgStatusMessage":"Session [997b7217c7aded99c924d37b8f64c662] was terminated due to FORWARDING_TO_NODE_FAILED"}}
ERROR: Error forwarding the new session Error forwarding the request Failed to connect to /10.44.0.227:25550
chrome
    at new RuntimeError (/var/jenkins_home/workspace/CAF_tooling-ui_PR-56-RUHHTX565JS3AOYRVDGJCEDHOPB6Y3OK7KZJXVGCC2FJ53PW4M7Q/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/var/jenkins_home/workspace/CAF_tooling-ui_PR-56-RUHHTX565JS3AOYRVDGJCEDHOPB6Y3OK7KZJXVGCC2FJ53PW4M7Q/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
    at Request.self.callback (/var/jenkins_home/workspace/CAF_tooling-ui_PR-56-RUHHTX565JS3AOYRVDGJCEDHOPB6Y3OK7KZJXVGCC2FJ53PW4M7Q/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/jenkins_home/workspace/CAF_tooling-ui_PR-56-RUHHTX565JS3AOYRVDGJCEDHOPB6Y3OK7KZJXVGCC2FJ53PW4M7Q/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/jenkins_home/workspace/CAF_tooling-ui_PR-56-RUHHTX565JS3AOYRVDGJCEDHOPB6Y3OK7KZJXVGCC2FJ53PW4M7Q/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by alex3305** [comment]
Possibly related: zalando/zalenium#939 ?
