### ISSUE TITLE
Multiple Selenium test failures with 3.141.59-p38, By.LinkText and RemoteWebDriver.findElementByLinkText no longer working.

### ISSUE THREAD

**Issue by Shana-Hoddy** [elgalu/docker-selenium#379]
Our tests had multiple failures upon upgrade to the latest version of docker-selenium. The tests all failed on the By.linkText and RemoteWebDriver.findElementByLinkText method calls

#### Operating System
Zalenium running Chrome latest version 81

#### Image version
elgalu

#### Docker version
3.141.59-p38

Selenium test runs report the error:
javascript error: this.each is not a function
*** Element info: {Using=link text, value=Add New Expense}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByLinkText(RemoteWebDriver.java:380)

**Comment by Shana-Hoddy** [comment]
We reverted to the prior version and everything is working now.
