### ISSUE TITLE
What happened with selenium:v2.45.0-ssh3?

### ISSUE THREAD

**Issue by cybermarkus1** [elgalu/docker-selenium#69]
Hello! Im running this on my docker container: 
```
# Selenium
docker run --name=spx_selenium_$BUILD_ID -d \
--link=spx_ui_$BUILD_ID:spx \
-e VNC_PASSWORD=pancakes \
--privileged \
-v /dev/shm:/dev/shm \
elgalu/selenium:v2.45.0-ssh3
```

I have noticed that you upgrade the version, but with the latest version im not able to run it. 

i got following error:
```

Using the selenium server at http://selenium:4444/wd/hub
[launcher] Running 1 instances of WebDriver

/usr/local/test/config/node_modules/selenium-webdriver/http/index.js:172
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED 172.17.0.5:4444
    at ClientRequest.<anonymous> (/usr/local/test/config/node_modules/selenium-webdriver/http/index.js:172:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/test/config/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/usr/local/test/config/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/usr/local/test/config/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/usr/local/test/config/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/usr/local/test/config/node_modules/protractor/lib/runner.js:182:37)
    at /usr/local/test/config/node_modules/protractor/lib/runner.js:263:21
    at _fulfilled (/usr/local/test/config/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/test/config/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/test/config/node_modules/q/q.js:759:13)
    at /usr/local/test/config/node_modules/q/q.js:525:49
```
What am i doing wrong?

Awesome job! Best

**Comment by elgalu** [comment]
Hi, sorry I removed some buggy old versions, latest versions changed port to `24444` in case people share the network interface so now you need to add `-p 4444:24444` to your command or connect to `selenium:24444` instead of `selenium:4444`. Other option (simpler) is to set the port during docker run with `-e SELENIUM_HUB_PORT=4444` so try this:

```sh
# Selenium
docker run --name=spx_selenium_$BUILD_ID -d \
  --link=spx_ui_$BUILD_ID:spx \
  -e VNC_PASSWORD=pancakes \
  -e SELENIUM_HUB_PORT=4444 \
  -v /dev/shm:/dev/shm \
elgalu/selenium:2.53.0f
```

And don't forget to wait before starting your tests, to avoid un-deterministic sleeps:

```sh
docker exec spx_selenium_$BUILD_ID wait_all_done 30s
```

Now start your tests.

**Comment by cybermarkus1** [comment]
Hi! i have been trying your code but for some reasons the following code is not able to reach selenium docker container and i dont know why.

Protractor docker run command
```
# Protractor
cd spp/ui_test
docker build -t docker-registry.smaato.net:5000/spx-protractor:$BUILD_ID .
docker run --name=spx_protractor_$BUILD_ID \
-e E2E_SUITE \
--link=spx_ui_$BUILD_ID:spx \
--link=spx_selenium_$BUILD_ID:selenium \
-v /mnt/spx/e2e:/usr/local/test/config/output \
docker-registry.smaato.net:5000/spx-protractor:$BUILD_ID
```

Protractor.conf
```
exports.config = {
  seleniumAddress: 'http://selenium:4444/wd/hub',
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
        args: [
            '--disable-gpu',
            '--disable-impl-side-painting',
            '--disable-gpu-sandbox',
            '--disable-accelerated-2d-canvas',
            '--disable-accelerated-jpeg-decoding',
            '--no-sandbox',
            '--test-type=ui'
            ],
    },
  },
  // e.g. : 'demo.js': ['../specs/demo.js']
  suites: require('./suites.env.json').SUITES,
  rootElement: 'div[ng-app]',
  baseUrl: 'http://spx:8080/publisherportal/',
  jasmineNodeOpts: {
    showColors: true,
```

From protractor docker container i can access to my page but will return the following error:

```

Using the selenium server at http://selenium:4444/wd/hub
[launcher] Running 1 instances of WebDriver
[launcher] Error: Error: Wait timed out after 50004ms
    at Array.forEach (native)
    at process._tickCallback (node.js:382:9)
From: Task: <anonymous wait>
    at /usr/local/test/specs/login/login.page.js:43:31
    at Array.forEach (native)
    at process._tickCallback (node.js:382:9)
[launcher] Process exited with error code 100
ERROR!! { [Error: protractor exited with code 100]
  message: 'protractor exited with code 100',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function: bound ] } }
ERROR, PLEASE VISIT http://docker-test02.smaatolabs.net:9876/result/report.html
[12:47:09] 'protractor' errored after 54 s
[12:47:09] Error in plugin 'gulp-protractor'
Message:
    protractor exited with code 100
```

Can you help me? 

Best

**Comment by elgalu** [comment]
Can you add `-e SELENIUM_HUB_PORT=4444` looks like you missed it from my previous comment ;)

**Comment by cybermarkus1** [comment]
is there! haha , 4th line!

**Comment by elgalu** [comment]
hehe sorry didn't see it, so now the error is different, is no longer `Error: ECONNREFUSED` but `Error: Wait timed out after 50004ms`

**Comment by elgalu** [comment]
there is not enough info to debug, anything interesting in http://docker-test02.smaatolabs.net:9876/result/report.html ?

**Comment by elgalu** [comment]
try this
https://github.com/teerapap/grunt-protractor-runner/issues/113#issuecomment-78211362

**Comment by cybermarkus1** [comment]
yes. i cannot reach it. returns 500 and i dont knkow why

**Comment by cybermarkus1** [comment]
directconnect was set to false in order to use selenium.

**Comment by elgalu** [comment]
If you can't access the logs better try locally first to see the [videos](https://github.com/elgalu/docker-selenium/blob/master/docs/videos.md#pull) or watch it live with [vnc](https://github.com/elgalu/docker-selenium#vnc)

**Comment by cybermarkus1** [comment]
Fixed! was a problem with my DDBB. Thanks a lot!
